### ISSUE TITLE
Ubuntu 18.04 psycopg2 error

### ISSUE THREAD

**Issue by ethan-nelson** [hotosm/tasking-manager#1356]
After install postgresql, postgis, and python3.6, I pip installed the requirements from the TM file. Everything installed okay. Once it came time to running the database migrations with alembic, I encountered an issue:

```
ubuntu@ip-XX-XX-XX-XX:~/tasking-manager$ venv/bin/python manage.py db upgrade

Traceback (most recent call last):
  File "manage.py", line 48, in <module>
    manager.run()
  File "/home/ubuntu/tasking-manager/venv/lib/python3.6/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/home/ubuntu/tasking-manager/venv/lib/python3.6/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/home/ubuntu/tasking-manager/venv/lib/python3.6/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/home/ubuntu/tasking-manager/venv/lib/python3.6/site-packages/flask_migrate/__init__.py", line 247, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/home/ubuntu/tasking-manager/venv/lib/python3.6/site-packages/alembic/command.py", line 254, in upgrade
    script.run_env()
  File "/home/ubuntu/tasking-manager/venv/lib/python3.6/site-packages/alembic/script/base.py", line 421, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/home/ubuntu/tasking-manager/venv/lib/python3.6/site-packages/alembic/util/pyfiles.py", line 93, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/ubuntu/tasking-manager/venv/lib/python3.6/site-packages/alembic/util/compat.py", line 64, in load_module_py
    module_id, path).load_module(module_id) 
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "migrations/env.py", line 99, in <module>
    run_migrations_online()
  File "migrations/env.py", line 81, in run_migrations_online
    poolclass=pool.NullPool)
  File "/home/ubuntu/tasking-manager/venv/lib/python3.6/site-packages/sqlalchemy/engine/__init__.py", line 428, in engine_from_config
    return create_engine(url, **options)
  File "/home/ubuntu/tasking-manager/venv/lib/python3.6/site-packages/sqlalchemy/engine/__init__.py", line 387, in create_engine
    return strategy.create(*args, **kwargs)
  File "/home/ubuntu/tasking-manager/venv/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 80, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/home/ubuntu/tasking-manager/venv/lib/python3.6/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 554, in dbapi
    import psycopg2
  File "/home/ubuntu/tasking-manager/venv/lib/python3.6/site-packages/psycopg2/__init__.py", line 50, in <module>
    from psycopg2._psycopg import (                     # noqa
ImportError: /home/ubuntu/tasking-manager/venv/lib/python3.6/site-packages/psycopg2/.libs/libresolv-2-c4c53def.5.so: symbol __res_maybe_init version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference
```

Upgrading alembic using pip to version 2.7.3.2 seems to have fixed it, i.e. `venv/bin/pip install psycopg2==2.7.3.2`

**Comment by xamanu** [comment]
Thanks @ethan-nelson. Filed a simple PR on this.
