### ISSUE TITLE
Getting errors when executing python tests in local instance

### ISSUE THREAD

**Issue by JorgeMartinezG** [hotosm/tasking-manager#1491]
Running the command ```python -m unittest discover tests/server``` on a fresh installation of the project, I receive this 4 errors. I also include the Traceback for each error for better debugging:

```
======================================================================
ERROR: test_gpx_xml_file_generated_correctly (integration.services.test_mapping_service.TestMappingService)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/unittest/mock.py", line 1204, in patched
    return func(*args, **keywargs)
  File "/usr/src/app/tests/server/integration/services/test_mapping_service.py", line 54, in test_gpx_xml_file_generated_correctly
    gpx_xml = MappingService.generate_gpx(1, '1,2', timestamp)
  File "/usr/src/app/server/services/mapping_service.py", line 182, in generate_gpx
    if not tasks or tasks.count() == 0:
TypeError: count() takes exactly one argument (0 given)

======================================================================
ERROR: test_osm_xml_file_generated_correctly (integration.services.test_mapping_service.TestMappingService)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/unittest/mock.py", line 1204, in patched
    return func(*args, **keywargs)
  File "/usr/src/app/tests/server/integration/services/test_mapping_service.py", line 93, in test_osm_xml_file_generated_correctly
    osm_xml = MappingService.generate_osm_xml(1, '1,2')
  File "/usr/src/app/server/services/mapping_service.py", line 213, in generate_osm_xml
    if not tasks or tasks.count() == 0:
TypeError: count() takes exactly one argument (0 given)

======================================================================
ERROR: test_invalidate_all_sets_counters_correctly (integration.services.test_validation_service.TestValidationService)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/src/app/tests/server/integration/services/test_validation_service.py", line 56, in test_invalidate_all_sets_counters_correctly
    ValidatorService.invalidate_all_tasks(self.test_project.id, self.test_user.id)
  File "/usr/src/app/server/services/validator_service.py", line 247, in invalidate_all_tasks
    task.unlock_task(user_id, new_state=TaskStatus.INVALIDATED)
  File "/usr/src/app/server/models/postgis/task.py", line 535, in unlock_task
    TaskInvalidationHistory.record_invalidation(self.project_id, self.id, user_id, history)
  File "/usr/src/app/server/models/postgis/task.py", line 79, in record_invalidation
    entry.mapper_id = last_mapped.user_id
AttributeError: 'NoneType' object has no attribute 'user_id'

======================================================================
ERROR: test_mapped_by_and_validated_by_are_null_after_invalidating_all (integration.services.test_validation_service.TestValidationService)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/src/app/tests/server/integration/services/test_validation_service.py", line 67, in test_mapped_by_and_validated_by_are_null_after_invalidating_all
    ValidatorService.invalidate_all_tasks(self.test_project.id, self.test_user.id)
  File "/usr/src/app/server/services/validator_service.py", line 247, in invalidate_all_tasks
    task.unlock_task(user_id, new_state=TaskStatus.INVALIDATED)
  File "/usr/src/app/server/models/postgis/task.py", line 535, in unlock_task
    TaskInvalidationHistory.record_invalidation(self.project_id, self.id, user_id, history)
  File "/usr/src/app/server/models/postgis/task.py", line 79, in record_invalidation
    entry.mapper_id = last_mapped.user_id
AttributeError: 'NoneType' object has no attribute 'user_id'
```

**Comment by JorgeMartinezG** [comment]
**Update:** 
- Integration tests are skipped on Circle CI, causing some errors not be seen when a Pull request is created. Thanks @ramyaragupathy 
- Pull request https://github.com/hotosm/tasking-manager/pull/1458 which had changes on project.py file, made ```./server/integration/models/postgis/testproject/test_project_can_be_cloned``` fail when tests are run locally, raising to a number of 29 errors in total. To be more specific, original project to be cloned, had null value on the _changeset_comment_ attribute, making https://github.com/hotosm/tasking-manager/blob/develop/server/models/postgis/project.py#L186 raise error. A proposed fix is defined above.
```
changeset_comments = []
if original_project.changeset_comment is not None:
changeset_comments = original_project.changeset_comment.split(' ')
```
- ```tests/server/integration/models/postgis/test_user.py``` did not have id attribute defined within tests. Including this attribute two tests.

**Comment by JorgeMartinezG** [comment]
*Update:*
- test_gpx_xml_file_generated_correctly and test_osm_xml_file_generated_correctly tests fail because the variable ```tasks``` is considered a list, instead of a python object. The curious thing is that a List object has method count, but requires an input argument. Modifying tasks.count() to len(tasks) fixes these tests.
- test_mapped_by_and_validated_by_are_null_after_invalidating_all fails because TaskHistory.get_last_mapped_action returns a **None** value. Making a condition based on this variable fixes the test.

**Comment by xamanu** [comment]
This has been merged and fixed. Thanks a lot @JorgeMartinezG.
