### ISSUE TITLE
CircleCI is not setting "TM_APP_BASE_URL" environment variable

### ISSUE THREAD

**Issue by arunasank** [hotosm/tasking-manager#1570]
We are seeing the following error, when you press the "Login" button on the TM:

```
// 20190514084934
> // https://tasks-stage.hotosm.org/api/v1/auth/login?redirect_to=/
>
> {
>   "<!DOCTYPE html>\n<html xmlns": "\"http://www.w3.org/1999/xhtml\">\n  <head>\n    <meta charset=\"utf-8\">\n    <title>OpenStreetMap</title>\n    <link rel=\"stylesheet\" media=\"screen\" href=\"/assets/errors-63b137588d8ef05030514126c94a898a3baac98ca7ea775df39bbc9d62cc7927.css\" />\n  </head>\n  <body>\n    <img class=\"logo\" src=\"/assets/osm_logo-ce691ac3325e0ebe119ff9087858192cc7677e50d7b77655cafc1f208161ad79.png\" />\n    <div class=\"details\">\n      <h1>Application error</h1>\n<p>The OpenStreetMap server encountered an unexpected condition that prevented it from fulfilling the request (HTTP 500)</p>\n<p>Feel free to <a href=\"http://wiki.openstreetmap.org/wiki/Contact\" title=\"Various contact channels explained\">contact</a> the OpenStreetMap community if your problem persists. Make a note of the exact URL / post data of your request.</p>\n<p>This may be a problem in our Ruby On Rails code. 500 occurs with exceptions thrown outside of an action (like in Dispatcher setups or broken Ruby code)</p>\n\n    </div>\n  </body>\n</html>\n"
> }

```

I checked the logs on the server, and saw this:
```
/tasking-manager/manage.py:26: UserWarning: TM_APP_BASE_URL environmental variable not set.
  warnings.warn("%s environmental variable not set." % (key,))
[2019-05-14 08:49:17,546] ERROR in app: Exception on /api/v1/auth/login [GET]
Traceback (most recent call last):
  File "/tasking-manager/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/tasking-manager/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/tasking-manager/venv/lib/python3.6/site-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/tasking-manager/venv/lib/python3.6/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/tasking-manager/venv/lib/python3.6/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/tasking-manager/server/api/users/authentication_apis.py", line 44, in get
    return osm.authorize(callback=f'{base_url}/api/v1/auth/oauth-callback{redirect_query}')
  File "/tasking-manager/venv/lib/python3.6/site-packages/flask_oauthlib/client.py", line 495, in authorize
    token = self.generate_request_token(callback)[0]
  File "/tasking-manager/venv/lib/python3.6/site-packages/flask_oauthlib/client.py", line 580, in generate_request_token
    data=data,
flask_oauthlib.client.OAuthException: Failed to generate request token
```

and confirmed that this is not getting set on CloudFormation:

<img width="782" alt="Screen Shot 2019-05-14 at 3 40 03 PM" src="https://user-images.githubusercontent.com/3166852/57690139-9c222e80-765e-11e9-8d5d-c71ab4e694c1.png">

We do attempt to set this in the CircleCi configuration, so maybe we aren't passing the right environment variables within circle ci?

https://github.com/hotosm/tasking-manager/blob/4b90fdfb6d8472343c9b7a49079e476a3db16f57/.circleci/config.yml#L227

and

https://github.com/hotosm/tasking-manager/blob/4b90fdfb6d8472343c9b7a49079e476a3db16f57/.circleci/config.yml#L130

cc/ @xamanu @dakotabenjamin

**Comment by arunasank** [comment]
Oh we're missing an underscore. Fixed this with new variables.

<img width="292" alt="Screen Shot 2019-05-14 at 3 45 54 PM" src="https://user-images.githubusercontent.com/3166852/57690978-a0e7e200-7660-11e9-9e6b-b364eb7e7ad0.png">

![gif](https://media.giphy.com/media/j2kABRVERmL8JFlmQl/giphy.gif)

**Comment by arunasank** [comment]
Rebuilt the stack, to eliminate this as the cause of error, but still seeing:
```
[2019-05-14 11:34:27,109] ERROR in app: Exception on /api/v1/auth/login [GET]
Traceback (most recent call last):
  File "/tasking-manager/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/tasking-manager/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/tasking-manager/venv/lib/python3.6/site-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/tasking-manager/venv/lib/python3.6/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/tasking-manager/venv/lib/python3.6/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/tasking-manager/server/api/users/authentication_apis.py", line 44, in get
    return osm.authorize(callback=f'{base_url}/api/v1/auth/oauth-callback{redirect_query}')
  File "/tasking-manager/venv/lib/python3.6/site-packages/flask_oauthlib/client.py", line 495, in authorize
    token = self.generate_request_token(callback)[0]
  File "/tasking-manager/venv/lib/python3.6/site-packages/flask_oauthlib/client.py", line 580, in generate_request_token
    data=data,
flask_oauthlib.client.OAuthException: Failed to generate request token
```

**Comment by dakotabenjamin** [comment]
Maybe we need to generate a new token pair?

**Comment by arunasank** [comment]
Fixed the login by generating a new token pair. @dakotabenjamin do tokens have expiry dates? Should they be regularly cycled?

**Comment by arunasank** [comment]
This is fixed!
