### ISSUE TITLE
Fix `projects/queries/myself/owner/` endpoint

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#2045]
It's returning on the console:

```
[2019-12-10 11:57:45,085] ERROR in app: Exception on /api/v2/projects/queries/myself/owner/ [GET]
Traceback (most recent call last):
  File "/home/wille/.virtualenvs/taskman/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/wille/.virtualenvs/taskman/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/wille/.virtualenvs/taskman/lib/python3.7/site-packages/flask_restful/__init__.py", line 462, in wrapper
    return self.make_response(data, code, headers=headers)
  File "/home/wille/.virtualenvs/taskman/lib/python3.7/site-packages/flask_restful/__init__.py", line 491, in make_response
    resp = self.representations[mediatype](data, *args, **kwargs)
  File "/home/wille/.virtualenvs/taskman/lib/python3.7/site-packages/flask_restful/representations/json.py", line 21, in output_json
    dumped = dumps(data, **settings) + "\n"
  File "/usr/lib64/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib64/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib64/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib64/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Campaign is not JSON serializable
```

**Comment by fitoria** [comment]
Could not reproduce this issue tried with different project statuses and all, it always returned 200. Seems to be fixed by other commit.

**Comment by willemarcel** [comment]
@fitoria I tested again and it's working correctly! Thank you!
