### ISSUE TITLE
Get interest detail endpoint is failing

### ISSUE THREAD

**Issue by willemarcel** [hotosm/tasking-manager#2655]
```
127.0.0.1 - - [06/Apr/2020 16:30:35] "OPTIONS /api/v2/interests/3/ HTTP/1.1" 200 -
[2020-04-06 16:30:35,429] ERROR in app: Exception on /api/v2/interests/3/ [GET]
Traceback (most recent call last):
  File "/home/wille/.virtualenvs/taskman/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/wille/.virtualenvs/taskman/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/wille/.virtualenvs/taskman/lib/python3.8/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/wille/.virtualenvs/taskman/lib/python3.8/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/wille/.virtualenvs/taskman/lib/python3.8/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/wille/.virtualenvs/taskman/lib/python3.8/site-packages/flask_httpauth.py", line 105, in decorated
    return f(*args, **kwargs)
  File "/home/wille/projects/HOT/tasking-manager/backend/api/interests/resources.py", line 150, in get
    if len(orgs_dto.organisation) < 1:
AttributeError: 'ListOrganisationsDTO' object has no attribute 'organisation'
```

**Comment by ritvikjain99** [comment]
This is probably due to it the field being 'organisations' instead of 'organisation'.
Similar to #2631
