### ISSUE TITLE
I am not able to run TM

### ISSUE THREAD

**Issue by qeef** [hotosm/tasking-manager#2827]
I wanted to run TM locally. I used the commands from https://github.com/hotosm/tasking-manager/blob/develop/docs/setup-docker.md:
- clone
- checkout to master
- copy example env
- set osm oauth key/secret

Then, I tested multiple options, like:
- `make bulid`
- `make up`

or:
- `docker-compose up`

When `docker-compose logs -f`, I do have the following error after looking at `http://127.0.0.1:5000/`:
```
app           | [2020-04-30 07:52:35,782] ERROR in app: Exception on / [GET]
app           | Traceback (most recent call last):
app           |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
app           |     response = self.full_dispatch_request()
app           |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
app           |     rv = self.handle_user_exception(e)
app           |   File "/usr/local/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
app           |     return cors_after_request(app.make_response(f(*args, **kwargs)))
app           |   File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 272, in error_router
app           |     return original_handler(e)
app           |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
app           |     reraise(exc_type, exc_value, tb)
app           |   File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
app           |     raise value
app           |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
app           |     rv = self.dispatch_request()
app           |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
app           |     return self.view_functions[rule.endpoint](**req.view_args)
app           |   File "/usr/src/app/backend/__init__.py", line 60, in index
app           |     return render_template("index.html")
app           |   File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 138, in render_template
app           |     ctx.app.jinja_env.get_or_select_template(template_name_or_list),
app           |   File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 930, in get_or_select_template
app           |     return self.get_template(template_name_or_list, parent, globals)
app           |   File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 883, in get_template
app           |     return self._load_template(name, self.make_globals(globals))
app           |   File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 857, in _load_template
app           |     template = self.loader.load(self, name, globals)
app           |   File "/usr/local/lib/python3.7/site-packages/jinja2/loaders.py", line 115, in load
app           |     source, filename, uptodate = self.get_source(environment, name)
app           |   File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 60, in get_source
app           |     return self._get_source_fast(environment, template)
app           |   File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 89, in _get_source_fast
app           |     raise TemplateNotFound(template)
app           | jinja2.exceptions.TemplateNotFound: index.html
app           | 172.24.0.1 - - [30/Apr/2020 07:52:35] "GET / HTTP/1.1" 500 -
app           | 172.24.0.1 - - [30/Apr/2020 07:52:35] "GET /favicon.ico HTTP/1.1" 404 -
```

And `http://127.0.0.1:5000/` says:
```
Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```

Any ideas what am I doing wrong?

**Comment by xamanu** [comment]
Hi @qeef, the `Makefile` deals with Docker and we are currently updating our setup for TM4 on this: https://github.com/hotosm/tasking-manager/pull/2816 Can you check if the PR works for you? Thank you.

**Comment by qeef** [comment]
```
docker-compose build --no-cache app
ERROR: Named volume "frontend:/usr/src/app:rw" is used in service "frontend" but no declaration was found in the volumes section.
make: *** [Makefile:13: build] Error 1
```

**Comment by qeef** [comment]
the same for `docker-compose up -d`

**Comment by qeef** [comment]
When I did
```
diff --git a/docker-compose.override.yml b/docker-compose.override.yml
index d719c8fa..1058e77b 100644
--- a/docker-compose.override.yml
+++ b/docker-compose.override.yml
@@ -27,7 +27,7 @@ services:
       args:
         - TM_APP_API_URL=http://localhost/api
     volumes:
-      - frontend/:/usr/src/app
+      - .:/usr/src/app
     command: npm start
     environment:
       - TM_APP_API_URL=http://localhost/api
```
The problem changed to
```
ERROR: Network web declared as external, but could not be found. Please create the network manually using `docker network create web` and try again.
```

**Comment by qeef** [comment]
I am not the docker expert, sorry.

**Comment by JorgeMartinezG** [comment]
Hello @qeef . Currently since the frontend/backend separation, the docker images do not compile successfully. We are working in the PR referenced above to modify the docker images in order to be compliant with latest setup. 

We would need to update the docs in order to include the external network for the reverse proxy we are using.

Thank you for raising this

**Comment by JorgeMartinezG** [comment]
Hey @qeef I´ve forced pushed the fixes related to the branch. The makefile now validates the external docker network. Please recreate the branch and execute `make up`

Also, you would need to remove the previous network. `docker network rm web`

**Comment by andodet** [comment]
I have just cloned the repo and tried to set up a dev-environment launching `make build` but apparently it tries to reach an `app` service that is nowhere to be found in both `docker-compose.*` files.  
Am I missing something or is there anything off with the Docker setup?
