### ISSUE TITLE
[bug] Login modal is blank on macOS Catalina

### ISSUE THREAD

**Issue by mireille-raad** [hotosm/tasking-manager#3485]
After clicking login in navigation, I see a pop-up. The form is blank.

<img width="1345" alt="Screen Shot 2020-08-16 at 6 11 37 PM" src="https://user-images.githubusercontent.com/521705/90344957-f9d4c180-dfeb-11ea-96e0-845d6e53f052.png">

I tried on multiple days, if I try like 20 times, sometimes it works. I am on macOS Catalina. I tested with Firefox, Chrome and Safari. I get this:

<img width="502" alt="Screen Shot 2020-08-16 at 6 09 48 PM" src="https://user-images.githubusercontent.com/521705/90344939-e45f9780-dfeb-11ea-8682-9ca58b21bf39.png">

<img width="505" alt="Screen Shot 2020-08-16 at 6 09 58 PM" src="https://user-images.githubusercontent.com/521705/90344940-e6295b00-dfeb-11ea-8cdd-4aaecf07bffb.png">

I looked at the console to see if any errors were logged, there is nothing.

I am not sure if there is something that I can add to this bug report more useful. Do others get the same blank screen?

**Comment by willemarcel** [comment]
I have noticed some problems on the login as well, but it worked on the second try.

There are some errors on the server log:

```
flask_oauthlib.client.OAuthException: Invalid response from osm

Traceback (most recent call last):
  File "/tasking-manager/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/tasking-manager/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/tasking-manager/venv/lib/python3.6/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/tasking-manager/venv/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/tasking-manager/venv/lib/python3.6/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/tasking-manager/backend/api/system/authentication.py", line 75, in get
    osm_resp = osm.authorized_response()
  File "/tasking-manager/venv/lib/python3.6/site-packages/flask_oauthlib/client.py", line 675, in authorized_response
    data = self.handle_oauth1_response()
  File "/tasking-manager/venv/lib/python3.6/site-packages/flask_oauthlib/client.py", line 620, in handle_oauth1_response
    type='invalid_response', data=data
```

**Comment by willemarcel** [comment]
@mireille-raad would you mind if I ask you to try to login on https://osmcha.org/ and on https://tasks-stage.hotosm.org/ in order to have more information about the error occurrence?

**Comment by mireille-raad** [comment]
@willemarcel can you replicate the bug? 

The login is working for me on the staging site. If it stops working or gives the blank screen again, I'll make sure to report back the time (or send you my IP privately), so you can take a look at the server logs.

**Comment by edwardgalligan** [comment]
Seeing the same issue on Firefox 81.0b9

Login works fine on Chrome.

Not sure if that helps reproducing.

**Comment by willemarcel** [comment]
I believe that was some temporary problem and is fixed.
