### ISSUE TITLE
[BUG] CircleCI backend code check failing

### ISSUE THREAD

**Issue by HelNershingThapa** [hotosm/tasking-manager#5395]
https://app.circleci.com/pipelines/github/hotosm/tasking-manager/9076/workflows/cb6e28f4-ac7c-4160-8769-c43888f03cb9/jobs/14041

```
#!/bin/bash -eo pipefail
cd ${CIRCLE_WORKING_DIRECTORY}
mkdir ${CIRCLE_WORKING_DIRECTORY}/tests/backend/lint
black --check manage.py backend tests migrations
flake8 manage.py backend tests migrations

All done! ✨ 🍰 ✨
277 files would be left unchanged.
Traceback (most recent call last):
  File "/home/circleci/.pyenv/versions/3.7.15/bin/flake8", line 8, in <module>
    sys.exit(main())
  File "/home/circleci/.pyenv/versions/3.7.15/lib/python3.7/site-packages/flake8/main/cli.py", line 22, in main
    app.run(argv)
  File "/home/circleci/.pyenv/versions/3.7.15/lib/python3.7/site-packages/flake8/main/application.py", line 363, in run
    self._run(argv)
  File "/home/circleci/.pyenv/versions/3.7.15/lib/python3.7/site-packages/flake8/main/application.py", line 350, in _run
    self.initialize(argv)
  File "/home/circleci/.pyenv/versions/3.7.15/lib/python3.7/site-packages/flake8/main/application.py", line 330, in initialize
    self.find_plugins(config_finder)
  File "/home/circleci/.pyenv/versions/3.7.15/lib/python3.7/site-packages/flake8/main/application.py", line 153, in find_plugins
    self.check_plugins = plugin_manager.Checkers(local_plugins.extension)
  File "/home/circleci/.pyenv/versions/3.7.15/lib/python3.7/site-packages/flake8/plugins/manager.py", line 357, in __init__
    self.namespace, local_plugins=local_plugins
  File "/home/circleci/.pyenv/versions/3.7.15/lib/python3.7/site-packages/flake8/plugins/manager.py", line 238, in __init__
    self._load_entrypoint_plugins()
  File "/home/circleci/.pyenv/versions/3.7.15/lib/python3.7/site-packages/flake8/plugins/manager.py", line 254, in _load_entrypoint_plugins
    eps = importlib_metadata.entry_points().get(self.namespace, ())
AttributeError: 'EntryPoints' object has no attribute 'get'

Exited with code exit status 1
CircleCI received exit code 1
```

**Screenshot**
![fail-sc](https://user-images.githubusercontent.com/51614993/198953409-02bbdff2-602a-4e3b-af30-c4b2abe4f4c2.png)

**Comment by Aadesh-Baral** [comment]
Probable solution:
https://stackoverflow.com/questions/73929564/entrypoints-object-has-no-attribute-get-digital-ocean

**Comment by Aadesh-Baral** [comment]
The solution i mentioned above fixed the issue on backend code check but now frontend test is failing with following error:
``` $ npm run preparation && npm run update-static && react-scripts build

> TaskingManager-frontend@0.1.0 preparation
> bash -c "if (test -a ../tasking-manager.env); then grep -hs ^ ../tasking-manager.env .env.expand > .env; else cp .env.expand .env; fi"


> TaskingManager-frontend@0.1.0 update-static
> bash -c "mkdir -p public/static/id; mkdir -p public/static/rapid; cp -R node_modules/@hotosm/id/dist/* public/static/id; if ! (test -a node_modules/RapiD/dist/RapiD.css) then mv node_modules/RapiD/dist/iD.css node_modules/RapiD/dist/RapiD.css; fi; cp -R node_modules/RapiD/dist/* public/static/rapid;"

node:internal/modules/cjs/loader:535
      throw e;
      ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/tokenize' is not defined by "exports" in /home/circleci/app/frontend/node_modules/postcss-safe-parser/node_modules/postcss/package.json
    at new NodeError (node:internal/errors:393:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:358:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:668:3)
    at resolveExports (node:internal/modules/cjs/loader:529:36)
    at Module._findPath (node:internal/modules/cjs/loader:569:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:981:27)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/circleci/app/frontend/node_modules/postcss-safe-parser/lib/safe-parser.js:1:17) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}

Node.js v18.12.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Exited with code exit status 1
CircleCI received exit code 1```
