### ISSUE TITLE
[BUG] Error while installing psycopg2

### ISSUE THREAD

**Issue by Aadesh-Baral** [hotosm/tasking-manager#5785]
Got following error while installing backend dependencies with pdm install.
```
ERRORS:
add psycopg2 failed:
Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/aadesh/.local/lib/python3.8/site-packages/pdm/installers/synchronizers.py", line 272, in install_candidate
    self.manager.install(can)
  File "/home/aadesh/.local/lib/python3.8/site-packages/pdm/installers/manager.py", line 33, in install
    installer(str(prepared.build()), self.environment, prepared.direct_url())
  File "/home/aadesh/.local/lib/python3.8/site-packages/pdm/models/candidates.py", line 373, in build
    self.wheel = Path(builder.build(build_dir, metadata_directory=self._metadata_dir))
  File "/home/aadesh/.local/lib/python3.8/site-packages/pdm/builders/wheel.py", line 28, in build
    filename = self._hook.build_wheel(out_dir, config_settings, metadata_directory)
  File "/home/aadesh/.local/lib/python3.8/site-packages/pyproject_hooks/_impl.py", line 209, in build_wheel
    return self._call_hook('build_wheel', {
  File "/home/aadesh/.local/lib/python3.8/site-packages/pyproject_hooks/_impl.py", line 311, in _call_hook
    self._subprocess_runner(
  File "/home/aadesh/.local/lib/python3.8/site-packages/pdm/builders/base.py", line 260, in subprocess_runner
    return log_subprocessor(cmd, cwd, extra_environ=env)
  File "/home/aadesh/.local/lib/python3.8/site-packages/pdm/builders/base.py", line 107, in log_subprocessor
    raise build_error(e) from None
pdm.exceptions.BuildError: Build backend raised error: Showing the last 10 lines of the build output:
It appears you are missing some prerequisite to build the package from source.

You may install a binary package by installing 'psycopg2-binary' from PyPI.
If you want to install psycopg2 from source, please install the packages
required for the build and try again.

For further information please check the 'doc/src/install.rst' file (also at
<https://www.psycopg.org/docs/install.html>).

error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1

See /tmp/pdm-install-q9nqpiax.log for detailed debug log.
[InstallationError]: Some package operations are not complete yet
Add '-v' to see the detailed traceback

```
Although I've already found the solution of this issue. Creating it for future references.

**Comment by Aadesh-Baral** [comment]
The two options listed below can be taken into consideration to resolve this issue.
- Install psycopg2-binary with `pdm add psycopg2-binary`.

OR

- Install python-dev for specific version of python you're using with `sudo apt-get install python3.x-dev`. [Replace x with the minor version]

**Comment by spwoodcock** [comment]
I think I understand why this is an issue now - apologies for not addressing it.

For development we need an option to run the server without docker.

One solution could be to `pdm add --dev pyscopg-binary`, then for development without docker the user would `pdm install --dev`.

That would keep `psycopg-binary` out of the production build.

**Comment by spwoodcock** [comment]
This has the issue that the development server does not replicate production completely, but it's a minor one.

It's probably a worthwhile tradeoff for ease of development.
