### ISSUE TITLE
[BUG] Routing error while trying to access live monitoring on dev setup

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/tasking-manager#6400]
**Describe the bug**
 While accessing the [live monitoring link](https://github.com/hotosm/tasking-manager/issues/6350) from the projects page, I get  `an error occured`  message in the frontend with the following console error:

```
RTLTextPlugin is loaded
react-dom.production.min.js:189 TypeError: n is not a function
    at tl (react-dom.production.min.js:240:251)
    at rl (react-dom.production.min.js:244:163)
    at xc (react-dom.production.min.js:284:388)
    at react-dom.production.min.js:283:409
    at Ec (react-dom.production.min.js:281:398)
    at cc (react-dom.production.min.js:273:439)
    at Go (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:267:273
ps @ react-dom.production.min.js:189
a.componentDidCatch.n.callback @ react-dom.production.min.js:190
Fa @ react-dom.production.min.js:144
wl @ react-dom.production.min.js:261
Al @ react-dom.production.min.js:260
Al @ react-dom.production.min.js:260
bl @ react-dom.production.min.js:259
(anonymous) @ react-dom.production.min.js:283
Ec @ react-dom.production.min.js:281
cc @ react-dom.production.min.js:273
Go @ react-dom.production.min.js:127
(anonymous) @ react-dom.production.min.js:267
Show 12 more frames
Show less
hooks.tsx:606 React Router caught the following error during render TypeError: n is not a function
    at tl (react-dom.production.min.js:240:251)
    at rl (react-dom.production.min.js:244:163)
    at xc (react-dom.production.min.js:284:388)
    at react-dom.production.min.js:283:409
    at Ec (react-dom.production.min.js:281:398)
    at cc (react-dom.production.min.js:273:439)
    at Go (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:267:273 {componentStack: '\n    at Ye (https://tasks-dev.hotosm.org/static/js…v.hotosm.org/static/js/main.26f08257.js:2:723383)'}
componentDidCatch @ hooks.tsx:606
a.componentDidCatch.n.callback @ react-dom.production.min.js:190
Fa @ react-dom.production.min.js:144
wl @ react-dom.production.min.js:261
Al @ react-dom.production.min.js:260
Al @ react-dom.production.min.js:260
bl @ react-dom.production.min.js:259
(anonymous) @ react-dom.production.min.js:283
Ec @ react-dom.production.min.js:281
cc @ react-dom.production.min.js:273
Go @ react-dom.production.min.js:127
(anonymous) @ react-dom.production.min.js:267
Show 12 more frames
Show less
```

**To Reproduce**
1. Go to https://tasks-dev.hotosm.org/projects/2
2. Click on `Live monitoring` link available after `Contributions timeline`
3. Now you get `An error occured` message in the frontend
4. Reload the page and the it loads fine

**Expected behavior**
Ideally there should be no routing error for live link and it should load fine in the first attempt. This error is not reproducible for other pages.

**Screenshots**
![underpass-dev](https://github.com/hotosm/tasking-manager/assets/12103383/74c9c8c3-ff11-4eca-ba58-b5d5d03def0b)

**Desktop (please complete the following information):**
 -  MacOS
 -  Chrome

**Comment by ramyaragupathy** [comment]
fixed through https://github.com/hotosm/tasking-manager/pull/6401
