### ISSUE TITLE
`gulp run` doesn't seem to work

### ISSUE THREAD

**Issue by pgiraud** [hotosm/tasking-manager#889]
When I run `gulp run` on my linux box, right after the browser is launched with localhost:3000 the command exits with the following error:

```[15:44:46] Using gulpfile ~/work/tasking-manager/client/gulpfile.js
[15:44:46] Starting 'run'...
[15:44:46] Starting 'create-dev-config'...
[15:44:46] Finished 'create-dev-config' after 28 ms
[15:44:46] Starting 'compile-sass'...
[15:44:46] Finished 'compile-sass' after 134 ms
[15:44:46] Starting 'browser-sync'...
[15:44:46] Finished 'browser-sync' after 33 ms
[15:44:46] Starting 'sass:watch'...
[15:44:46] Finished 'sass:watch' after 20 ms
[15:44:46] Finished 'run' after 218 ms
[Browsersync] Access URLs:
 ------------------------------------
       Local: http://localhost:3000
    External: http://172.20.10.2:3000
 ------------------------------------
          UI: http://localhost:3001
 UI External: http://172.20.10.2:3001
 ------------------------------------
[Browsersync] Serving files from: ./
[Browsersync] Watching files...
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: watch node_modules/core-js/library/modules/es6.array.copy-within.js ENOSPC
    at exports._errnoException (util.js:1029:11)
    at FSWatcher.start (fs.js:1399:19)
    at Object.fs.watch (fs.js:1425:11)
    at createFsWatchInstance (/home/pierre/work/tasking-manager/client/node_modules/browser-sync/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/pierre/work/tasking-manager/client/node_modules/browser-sync/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/pierre/work/tasking-manager/client/node_modules/browser-sync/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleFile (/home/pierre/work/tasking-manager/client/node_modules/browser-sync/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at FSWatcher.<anonymous> (/home/pierre/work/tasking-manager/client/node_modules/browser-sync/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at FSReqWrap.oncomplete (fs.js:114:15)
```

Can someone please confirm that I'm not the only one with such an error?

I have:
npm 5.5.1
gulp 3.9.1

**Comment by alekno** [comment]
On windows it runs:

```
 gulp run
[19:39:11] Using gulpfile ~\source\repos\tasking-manager\client\gulpfile.js
[19:39:11] Starting 'run'...
[19:39:11] Starting 'create-dev-config'...
[19:39:11] Finished 'create-dev-config' after 85 ms
[19:39:11] Starting 'compile-sass'...
[19:39:14] Finished 'compile-sass' after 2.66 s
[19:39:14] Starting 'browser-sync'...
[19:39:15] Finished 'browser-sync' after 1.05 s
[19:39:15] Starting 'sass:watch'...
[19:39:15] Finished 'sass:watch' after 62 ms
[19:39:15] Finished 'run' after 3.88 s
[Browsersync] Access URLs:
 -------------------------------------
       Local: http://localhost:3000
    External: http://192.168.56.1:3000
 -------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.56.1:3001
 -------------------------------------
[Browsersync] Serving files from: ./
[Browsersync] Watching files...
```

**Comment by pgiraud** [comment]
What version of node, npm and gulp are you running?
Did the browser open and do pages appear?

**Comment by alekno** [comment]
npm@3.10.10
gulp 3.9.1
node v6.11.4

**Comment by dkocich** [comment]
On Ubuntu it runs
```
~/git/tasking-manager/client$ gulp run
[08:22:44] Using gulpfile ~/git/tasking-manager/client/gulpfile.js
[08:22:44] Starting 'run'...
[08:22:44] Starting 'create-dev-config'...
[08:22:44] Finished 'create-dev-config' after 33 ms
[08:22:44] Starting 'compile-sass'...
[08:22:44] Finished 'compile-sass' after 108 ms
[08:22:44] Starting 'browser-sync'...
[08:22:44] Finished 'browser-sync' after 28 ms
[08:22:44] Starting 'sass:watch'...
[08:22:45] Finished 'sass:watch' after 14 ms
[08:22:45] Finished 'run' after 185 ms
[Browsersync] Access URLs:
 --------------------------------------
       Local: http://localhost:3000
    External: http://192.168.2.202:3000
 --------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.2.202:3001
 --------------------------------------
[Browsersync] Serving files from: ./
[Browsersync] Watching files...
```
node v8.1.4
npm v5.5.1
gulp v3.9.1

**Comment by pgiraud** [comment]
Works on my mac personal computer. I will dig into it if possible (upgrading to node 8 maybe). Closing. Please reopen if you also have the same issue.
